{
 "title": "Cartridge Fill Level",
 "time": { "from": "2023-08-01T22:00:00.500Z", "to": "2023-08-03T21:59:59.500Z" },
 "templating": {
  "list": [
   {
    "name": "batchname",
    "label": "Batch Name",
    "query": "select distinct batchname from batch\n"
   },
   {
    "name": "Inspection_name",
    "label": "Inspection Name",
    "query": "SELECT DISTINCT inspectionname\nFROM batch"
   },
   {
    "name": "triggerindex",
    "label": "triggerindex",
    "query": "select distinct triggerindex from trigger\n order by triggerindex  asc"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "\n<!DOCTYPE html>\n<html>\n<head>\n<style>\n.theme-dark{\n  background-color:white;\n}\n.theme-light{\n  background-color:white;\n}\n.css-g43m4k{\nbackground-color: #A9A9A9;\nborder-radius: 50%;\nwidth: 15px;\nheight:15px;\nmargin-bottom:2px;\nmargin-right:2px;\n}\n\n</style>\n</head>\n<body>\n\n<div style=\"background-color:#F5F3F1;\">\n<a href=\"http://168.119.114.146/grafana/dashboards\">\n<img style=\"width:120px;background-color:#F5F3F1;padding-right:30px;\" src=\"public/img/logo_black.png\"></img></a>\n\n<h1 style=\"font-size: 20px;font-family:Arial;font-weight:bold;color:black;display:inline-block;padding-top:10px;padding-left:30%;position:center; text-align:center;\"for=\"html\">Cartridge Fill Level </h1>\n</div>\n\n</body>\n</html> \n\n\n\n\n\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Average Time Series",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {
     "rawSql": "SELECT\n  TO_TIMESTAMP(trigger.timestamp, 'YYYY-MM-DD HH24:MI') AS \"time\",\n  AVG(trigger.data1_1) AS \"avg_data1_1\",\n  AVG(data2_1) AS \"avg_data2_1\",\n  AVG(data3_1) AS \"avg_data3_1\",\n  AVG(data4_1) AS \"avg_data4_1\",\n  AVG(data5_1) AS \"avg_data5_1\",\n  AVG(data6_1) AS \"avg_data6_1\",\n  AVG(data7_1) AS \"avg_data7_1\",\n  AVG(data8_1) AS \"avg_data8_1\",\n  AVG(data9_1) AS \"avg_data9_1\"\nFROM\n  trigger\n  LEFT JOIN batch ON trigger.batch_inspectionid = batch.batch_inspectionid\nWHERE\n  TO_TIMESTAMP(trigger.timestamp, 'YYYY-MM-DD HH24:MI:SS.MS') >= $__timeFrom() AND\n  TO_TIMESTAMP(trigger.timestamp, 'YYYY-MM-DD HH24:MI:SS.MS') <= $__timeTo() AND\n  batch.batchname = '$batchname' AND\n  batch.inspectionname = '$Inspection_name'  \n\nGROUP BY \"time\"\nORDER BY \"time\" ASC\nLIMIT 100;\n"
    }
   ]
  },
  {
   "title": "Psition (x,y)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  --trigger.triggerindex,\n  trigger.data1_1 AS \"1,1\",\n  trigger.data2_1 AS \"2,1\",\n  trigger.data3_1 AS \"3,1\",\n  trigger.data4_1 AS \"4,1\",\n  trigger.data5_1 AS \"5,1\",\n  trigger.data6_1 AS \"6,1\",\n  trigger.data7_1 AS \"7,1\",\n  trigger.data8_1 AS \"8,1\",\n  trigger.data9_1 AS \"9,1\",\n  trigger.timestamp\nFROM\n  trigger\n  LEFT JOIN batch ON trigger.batch_inspectionid = batch.batch_inspectionid\nWHERE\n  TO_TIMESTAMP(trigger.timestamp, 'YYYY-MM-DD HH24:MI:SS.FF3') >= $__timeFrom() AND\n  TO_TIMESTAMP(trigger.timestamp, 'YYYY-MM-DD HH24:MI:SS.FF3') <= $__timeTo() AND\n  batch.batchname = '$batchname' AND\n  batch.inspectionname = '$Inspection_name' AND\n  trigger.triggerindex = '$triggerindex' AND\n  (trigger.data1_1 <> 0 OR\n   trigger.data2_1 <> 0 OR\n   trigger.data3_1 <> 0 OR\n   trigger.data4_1 <> 0 OR\n   trigger.data5_1 <> 0 OR\n   trigger.data6_1 <> 0 OR\n   trigger.data7_1 <> 0 OR\n   trigger.data8_1 <> 0 OR\n   trigger.data9_1 <> 0);\n\n"
    }
   ]
  },
  {
   "title": "Total Amounts",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n    (avg_data.\"1,1\" + avg_data.\"2,1\" + avg_data.\"3,1\" + avg_data.\"4,1\" + avg_data.\"5,1\" + avg_data.\"6,1\" + avg_data.\"7,1\" + avg_data.\"8,1\" + avg_data.\"9,1\") / 9 AS \"avg\",\n    GREATEST(avg_data.max_1_1, avg_data.max_2_1, avg_data.max_3_1, avg_data.max_4_1, avg_data.max_5_1, avg_data.max_6_1, avg_data.max_7_1, avg_data.max_8_1, avg_data.max_9_1) AS \"max\",\n    LEAST(avg_data.min_1_1, avg_data.min_2_1, avg_data.min_3_1, avg_data.min_4_1, avg_data.min_5_1, avg_data.min_6_1, avg_data.min_7_1, avg_data.min_8_1, avg_data.min_9_1) AS \"min\",\n    SQRT((avg_data.stddev_1_1^2 + avg_data.stddev_2_1^2 + avg_data.stddev_3_1^2 + avg_data.stddev_4_1^2 + avg_data.stddev_5_1^2 + avg_data.stddev_6_1^2 + avg_data.stddev_7_1^2 + avg_data.stddev_8_1^2 + avg_data.stddev_9_1^2) / 9) AS \"stddev\"\nFROM \n    (\n    SELECT \n        AVG(data1_1) AS \"1,1\", MAX(data1_1) AS max_1_1, MIN(data1_1) AS min_1_1, STDDEV(data1_1) AS stddev_1_1,\n        AVG(data2_1) AS \"2,1\", MAX(data2_1) AS max_2_1, MIN(data2_1) AS min_2_1, STDDEV(data2_1) AS stddev_2_1,\n        AVG(data3_1) AS \"3,1\", MAX(data3_1) AS max_3_1, MIN(data3_1) AS min_3_1, STDDEV(data3_1) AS stddev_3_1,\n        AVG(data4_1) AS \"4,1\", MAX(data4_1) AS max_4_1, MIN(data4_1) AS min_4_1, STDDEV(data4_1) AS stddev_4_1,\n        AVG(data5_1) AS \"5,1\", MAX(data5_1) AS max_5_1, MIN(data5_1) AS min_5_1, STDDEV(data5_1) AS stddev_5_1,\n        AVG(data6_1) AS \"6,1\", MAX(data6_1) AS max_6_1, MIN(data6_1) AS min_6_1, STDDEV(data6_1) AS stddev_6_1,\n        AVG(data7_1) AS \"7,1\", MAX(data7_1) AS max_7_1, MIN(data7_1) AS min_7_1, STDDEV(data7_1) AS stddev_7_1,\n        AVG(data8_1) AS \"8,1\", MAX(data8_1) AS max_8_1, MIN(data8_1) AS min_8_1, STDDEV(data8_1) AS stddev_8_1,\n        AVG(data9_1) AS \"9,1\", MAX(data9_1) AS max_9_1, MIN(data9_1) AS min_9_1, STDDEV(data9_1) AS stddev_9_1\n    FROM trigger\n    ) AS avg_data \n\n"
    }
   ]
  }
 ]
}