apiVersion: 1
groups:
    - orgId: 1
      name: services
      folder: Services
      interval: 1m
      rules:
        - uid: fd34e430-d810-4e80-a626-ac2bd0ba1ee5
          title: Deviation Treshold
          condition: E
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: P6E58CF9E1F3FE3DC
              model:
                datasource:
                    type: postgres
                    uid: P6E58CF9E1F3FE3DC
                editorMode: code
                format: table
                hide: false
                intervalMs: 1000
                maxDataPoints: 43200
                rawQuery: true
                rawSql: select trigger.data3_1 from trigger
                refId: A
                sql:
                    columns:
                        - parameters: []
                          type: function
                    groupBy:
                        - property:
                            type: string
                          type: groupBy
                    limit: 50
            - refId: D
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: P6E58CF9E1F3FE3DC
              model:
                datasource:
                    type: postgres
                    uid: P6E58CF9E1F3FE3DC
                editorMode: code
                format: table
                hide: false
                intervalMs: 1000
                maxDataPoints: 43200
                rawQuery: true
                rawSql: 'select trigger.data4_1 from trigger '
                refId: D
                sql:
                    columns:
                        - parameters: []
                          type: function
                    groupBy:
                        - property:
                            type: string
                          type: groupBy
                    limit: 50
            - refId: B
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 0
                            - 0
                        type: gt
                      operator:
                        type: and
                      query:
                        params: []
                      reducer:
                        params: []
                        type: avg
                      type: query
                datasource:
                    name: Expression
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                reducer: mean
                refId: B
                type: reduce
            - refId: C
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 0
                            - 0
                        type: gt
                      operator:
                        type: and
                      query:
                        params: []
                      reducer:
                        params: []
                        type: avg
                      type: query
                datasource:
                    name: Expression
                    type: __expr__
                    uid: __expr__
                expression: D
                intervalMs: 1000
                maxDataPoints: 43200
                reducer: mean
                refId: C
                type: reduce
            - refId: E
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 0
                            - 0
                        type: gt
                      operator:
                        type: and
                      query:
                        params: []
                      reducer:
                        params: []
                        type: avg
                      type: query
                datasource:
                    name: Expression
                    type: __expr__
                    uid: __expr__
                expression: $B > 70
                hide: false
                intervalMs: 1000
                maxDataPoints: 43200
                refId: E
                type: math
            - refId: F
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 0
                            - 0
                        type: gt
                      operator:
                        type: and
                      query:
                        params: []
                      reducer:
                        params: []
                        type: avg
                      type: query
                datasource:
                    name: Expression
                    type: __expr__
                    uid: __expr__
                expression: $D > 300
                hide: false
                intervalMs: 1000
                maxDataPoints: 43200
                refId: F
                type: math
          noDataState: OK
          execErrState: Error
          for: 5m
          labels:
            deviation: mean
          isPaused: false
